#!/usr/bin/env python3
"""Aggregate GitHub stats for the research repos and write _data/github_stats.yml.

The repo list is derived from the `code:` URLs in _data/publications.yml, so a
paper with a repo is counted the moment it is added and there is no second list
to keep in sync. A repo linked from several papers is fetched once.

Unlike Google Scholar, this needs no third-party provider — it is GitHub's own
REST API. GITHUB_TOKEN (set automatically inside Actions) lifts the rate limit
from 60 to 5,000 requests an hour; without it the script still works, since a
run costs two calls per repo.

The output is generated at build time and gitignored — nothing here is ever
committed. Run by .github/workflows/deploy.yml immediately before `jekyll build`,
so the numbers reach gh-pages baked into the HTML.

A failure cannot break the build: it warns, removes any existing output file, and
exits 0, which makes _layouts/publications.liquid drop the section this feeds (it
gates on `available`). Removing rather than keeping the previous file is
deliberate — a stale local copy must not get baked into a deploy. Pass --strict
to exit non-zero instead, which is what you want when running this by hand.
"""

from __future__ import annotations

import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import Request, urlopen

REPO_ROOT = Path(__file__).resolve().parents[2]
PUBLICATIONS_FILE = REPO_ROOT / "_data" / "publications.yml"
OUTPUT_FILE = REPO_ROOT / "_data" / "github_stats.yml"

API_ROOT = "https://api.github.com"


def yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def warn(message: str) -> None:
    """Annotate the Actions run, and stay readable on a terminal."""
    print(f"::warning title=Stats unavailable::{message}")
    print(f"WARNING: {message}", file=sys.stderr)


# A `code:` entry at any indent, pointing at a GitHub repo. Anchored at the key
# so the commented-out `code      : repo URL` line in the file header, and any
# other URL field, are both ignored. Trailing "/" and ".git" are trimmed so two
# spellings of the same repo collapse to one.
CODE_URL_RE = re.compile(
    r"^\s*code:\s*[\"']?https?://(?:www\.)?github\.com/"
    r"([\w.-]+/[\w.-]+?)(?:\.git)?/?[\"']?\s*$",
    re.IGNORECASE,
)


def read_repo_list(path: Path) -> list[str]:
    """Every distinct GitHub repo linked from a publication, in file order."""
    repos = []
    for line in path.read_text(encoding="utf-8").splitlines():
        match = CODE_URL_RE.match(line)
        if match and match.group(1) not in repos:
            repos.append(match.group(1))

    if not repos:
        raise RuntimeError(f"No code repos found in {path.relative_to(REPO_ROOT)}")
    return repos


def api_get(path: str) -> object:
    headers = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "veedata.github.io-stats",
    }
    token = os.getenv("GITHUB_TOKEN", "").strip()
    if token:
        headers["Authorization"] = f"Bearer {token}"

    with urlopen(Request(f"{API_ROOT}{path}", headers=headers), timeout=30) as response:
        return json.loads(response.read().decode("utf-8"))


def fetch_repo(full_name: str) -> dict:
    payload = api_get(f"/repos/{full_name}")

    # Contributor logins, so the aggregate counts a person once even when they
    # show up in several repos.
    contributors = api_get(f"/repos/{full_name}/contributors?per_page=100&anon=0")
    logins = {
        c.get("login")
        for c in (contributors if isinstance(contributors, list) else [])
        if c.get("login")
    }

    return {
        "name": payload.get("name", ""),
        "full_name": payload.get("full_name", full_name),
        "url": payload.get("html_url", f"https://github.com/{full_name}"),
        "description": (payload.get("description") or "").strip(),
        "language": payload.get("language") or "",
        "stars": int(payload.get("stargazers_count", 0)),
        "forks": int(payload.get("forks_count", 0)),
        "open_issues": int(payload.get("open_issues_count", 0)),
        "pushed_at": payload.get("pushed_at") or "",
        "contributors": sorted(logins),
    }


def render_yaml(data: dict) -> str:
    totals = data["totals"]
    lines = [
        "# Auto-generated by .github/scripts/fetch_github_stats.py — do not edit by hand.",
        f"available: {'true' if data['available'] else 'false'}",
        f"updated_at: {yaml_quote(data['updated_at'])}",
        "totals:",
        f"  repos: {totals['repos']}",
        f"  stars: {totals['stars']}",
        f"  forks: {totals['forks']}",
        f"  contributors: {totals['contributors']}",
        f"  last_pushed_at: {yaml_quote(totals['last_pushed_at'])}",
        "repos:",
    ]

    for repo in data["repos"]:
        lines.extend(
            [
                f"  - name: {yaml_quote(repo['name'])}",
                f"    full_name: {yaml_quote(repo['full_name'])}",
                f"    url: {yaml_quote(repo['url'])}",
                f"    description: {yaml_quote(repo['description'])}",
                f"    language: {yaml_quote(repo['language'])}",
                f"    stars: {repo['stars']}",
                f"    forks: {repo['forks']}",
                f"    open_issues: {repo['open_issues']}",
                f"    pushed_at: {yaml_quote(repo['pushed_at'])}",
                f"    contributors: {len(repo['contributors'])}",
            ]
        )

    return "\n".join(lines) + "\n"


def fetch() -> str:
    repo_names = read_repo_list(PUBLICATIONS_FILE)
    repos = [fetch_repo(name) for name in repo_names]
    repos.sort(key=lambda r: (-r["stars"], r["name"].lower()))

    everyone = set()
    for repo in repos:
        everyone.update(repo["contributors"])

    data = {
        "available": True,
        "updated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "totals": {
            "repos": len(repos),
            "stars": sum(r["stars"] for r in repos),
            "forks": sum(r["forks"] for r in repos),
            "contributors": len(everyone),
            "last_pushed_at": max((r["pushed_at"] for r in repos), default=""),
        },
        "repos": repos,
    }

    # Rendered in full before the write, so a mid-fetch failure never leaves a
    # half-populated file behind.
    OUTPUT_FILE.write_text(render_yaml(data), encoding="utf-8")
    totals = data["totals"]
    return (
        f"{totals['repos']} repos, {totals['stars']} stars, "
        f"{totals['forks']} forks, {totals['contributors']} unique contributors"
    )


def main(argv: list[str]) -> int:
    try:
        summary = fetch()
    except Exception as exc:  # noqa: BLE001 — any failure degrades the same way
        OUTPUT_FILE.unlink(missing_ok=True)
        warn(f"GitHub stats unavailable: {exc}")
        return 1 if "--strict" in argv else 0

    print(f"Updated {OUTPUT_FILE.relative_to(REPO_ROOT)}: {summary}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
