#!/usr/bin/env python3
"""Fetch Google Scholar author stats via SerpAPI and write _data/scholar_stats.yml.
The profile is taken from the Google Scholar link in _data/socials.yml. SerpAPI is required.

The output is generated at build time and gitignored — nothing here is ever
committed. Run by .github/workflows/deploy.yml immediately before `jekyll build`,
so the numbers reach gh-pages baked into the HTML.

A failure cannot break the build: it warns, removes any existing output file, and
exits 0, which makes _layouts/publications.liquid drop the section this feeds (it
gates on `available`). Removing rather than keeping the previous file is
deliberate — a stale local copy must not get baked into a deploy. Pass --strict
to exit non-zero instead, which is what you want when running this by hand.
"""

from __future__ import annotations

import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlencode
from urllib.request import urlopen

REPO_ROOT = Path(__file__).resolve().parents[2]
SOCIALS_FILE = REPO_ROOT / "_data" / "socials.yml"
OUTPUT_FILE = REPO_ROOT / "_data" / "scholar_stats.yml"

METRIC_KEYS = (
    "citations",
    "citations_since",
    "h_index",
    "h_index_since",
    "i10_index",
    "i10_index_since",
    "since_year",
)


def yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def warn(message: str) -> None:
    """Annotate the Actions run, and stay readable on a terminal."""
    print(f"::warning title=Stats unavailable::{message}")
    print(f"WARNING: {message}", file=sys.stderr)


def extract_scholar_url(socials_path: Path) -> str:
    text = socials_path.read_text(encoding="utf-8")
    match = re.search(r"https://scholar\.google\.com/citations\?[^\"'\s]+", text)
    if not match:
        raise RuntimeError("Could not find a Google Scholar URL in _data/socials.yml")
    return match.group(0)


def extract_author_id(scholar_url: str) -> str:
    match = re.search(r"[?&]user=([A-Za-z0-9_-]+)", scholar_url)
    if not match:
        raise RuntimeError(f"Could not parse the Scholar user ID from URL: {scholar_url}")
    return match.group(1)


def to_int(value: object) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        digits = re.sub(r"[^0-9]", "", value)
        return int(digits) if digits else None
    return None


def read_cited_by_metrics(payload: dict) -> dict:
    table = payload.get("cited_by", {}).get("table", [])
    metrics = {key: None for key in METRIC_KEYS}

    for row in table:
        for metric_key in ("citations", "h_index", "i10_index"):
            if metric_key not in row:
                continue
            metric_obj = row.get(metric_key, {})
            metrics[metric_key] = to_int(metric_obj.get("all"))

            since_key = next((k for k in metric_obj if k.startswith("since_")), None)
            if since_key:
                metrics[f"{metric_key}_since"] = to_int(metric_obj.get(since_key))
                year = since_key.replace("since_", "")
                if metrics["since_year"] is None and year.isdigit():
                    metrics["since_year"] = int(year)

    return metrics


def read_yearly_graph(payload: dict) -> list[dict]:
    """Citations per year, oldest first — the year-over-year bar chart's data."""
    rows = []
    for point in payload.get("cited_by", {}).get("graph", []):
        year = to_int(point.get("year"))
        citations = to_int(point.get("citations"))
        if year is None or citations is None:
            continue
        rows.append({"year": year, "citations": citations})

    rows.sort(key=lambda row: row["year"])
    return rows


def fetch_author_payload(author_id: str, api_key: str) -> dict:
    query = urlencode(
        {
            "engine": "google_scholar_author",
            "author_id": author_id,
            "hl": "en",
            "api_key": api_key,
        }
    )
    with urlopen(f"https://serpapi.com/search.json?{query}", timeout=30) as response:
        payload = json.loads(response.read().decode("utf-8"))

    if payload.get("error"):
        raise RuntimeError(f"SerpAPI error: {payload['error']}")

    return payload


def render_yaml(data: dict) -> str:
    lines = [
        "# Auto-generated by .github/scripts/fetch_scholar_stats.py — do not edit by hand.",
        f"available: {'true' if data['available'] else 'false'}",
        f"updated_at: {yaml_quote(data['updated_at'])}",
        f"source: {yaml_quote('serpapi')}",
        f"source_url: {yaml_quote(data['source_url'])}",
        f"author_id: {yaml_quote(data['author_id'])}",
        f"name: {yaml_quote(data['name'])}",
        f"affiliations: {yaml_quote(data['affiliations'])}",
    ]

    for key in METRIC_KEYS:
        value = data.get(key)
        lines.append(f"{key}: {'null' if value is None else value}")

    graph = data.get("graph") or []
    if not graph:
        lines.append("graph: []")
    else:
        lines.append("graph:")
        lines.extend(
            f"  - {{ year: {row['year']}, citations: {row['citations']} }}" for row in graph
        )

    return "\n".join(lines) + "\n"


def fetch() -> str:
    api_key = os.getenv("SERPAPI_KEY", "").strip()
    if not api_key:
        raise RuntimeError("SERPAPI_KEY is not set — add it as a repository secret")

    scholar_url = extract_scholar_url(SOCIALS_FILE)
    author_id = extract_author_id(scholar_url)

    payload = fetch_author_payload(author_id, api_key)
    author = payload.get("author", {})
    metrics = read_cited_by_metrics(payload)
    graph = read_yearly_graph(payload)

    if metrics["citations"] is None:
        raise RuntimeError("SerpAPI response contained no citation totals")

    data = {
        "available": True,
        "updated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "source_url": scholar_url,
        "author_id": author_id,
        "name": str(author.get("name", "")).strip(),
        "affiliations": str(author.get("affiliations", "")).strip(),
        "graph": graph,
        **metrics,
    }

    OUTPUT_FILE.write_text(render_yaml(data), encoding="utf-8")
    return (
        f"{author_id}: {data['citations']} citations, h-index {data['h_index']}, "
        f"i10 {data['i10_index']}, {len(graph)} years of history"
    )


def main(argv: list[str]) -> int:
    try:
        summary = fetch()
    except Exception as exc:  # noqa: BLE001 — any failure degrades the same way
        OUTPUT_FILE.unlink(missing_ok=True)
        warn(f"Scholar stats unavailable: {exc}")
        return 1 if "--strict" in argv else 0

    print(f"Updated {OUTPUT_FILE.relative_to(REPO_ROOT)}: {summary}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
