name: Deploy site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "47 5 * * 0"

permissions:
  contents: write

# Keep the later of the two in case of 2 consequent pushes.
concurrency:
  group: deploy-pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0"
          bundler-cache: true

      - name: Setup Python
        if: github.event_name != 'pull_request'
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      # Run the scripts to generate _data/*_stats.yml.
      - name: Fetch GitHub stats
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 .github/scripts/fetch_github_stats.py

      - name: Fetch Scholar stats
        if: github.event_name != 'pull_request'
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: python3 .github/scripts/fetch_scholar_stats.py

      - name: Install and Build 🔧
        run: |
          export JEKYLL_ENV=production
          bundle exec jekyll build

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
